module ReliabilityManager

using ..H2MainExt.ConfigLoader: ModelConfig

# ROMInterpolator のインポート
try
    using ROMInterpolator
catch
    if !isdefined(Main, :ROMInterpolator)
        path = joinpath(@__DIR__, "..", "ROMInterpolator", "ROMInterpolator.jl")
        Main.eval(:(include($path)))
    end
    using Main.ROMInterpolator
end

using .ROMInterpolator: AbstractInterpolator, evaluate_rom, get_tmax
using JLD2

export is_reliable, get_fitness, solve_thermal_fvm, verify_elites

"""
    is_reliable(model::AbstractInterpolator, mu::Vector{Float64})::Bool

ROMモデルの訓練範囲外(外挿領域)にあるかを判定する。
"""
function is_reliable(model::AbstractInterpolator, mu::Vector{Float64})::Bool
    return ROMInterpolator.is_reliable(model, mu)
end

"""
    solve_thermal_fvm(mu::Vector{Float64}, config::ModelConfig)::Float64

FVMソルバーを呼び出して実際の熱解析を実行し、最高温度を返す。
ソルバーの実行が失敗した、もしくはタイムアウトした場合は、適合度を `Inf`（ペナルティ）として返す。
"""
function solve_thermal_fvm(mu::Vector{Float64}, config::ModelConfig)::Float64
    # q3d が Main に定義されているか、あるいはロードを試みる
    if !isdefined(Main, :q3d)
        path = abspath(joinpath(@__DIR__, "../../../H2-main-ext/src/heat3ds.jl"))
        if isfile(path)
            try
                ENV["GKSwstype"] = "100"
                Main.eval(:(include($path)))
            catch e
                @warn "Failed to load heat3ds.jl: $e"
            end
        end
    end

    if !isdefined(Main, :q3d)
        @warn "FVM solver q3d is not defined. Returning Inf."
        return Inf
    end

    temp_snapshot = tempname() * ".jld2"
    
    # q3d は config.json と tsv_config.json をカレントディレクトリから要求するため、
    # 存在しない場合は実行できない。
    if !isfile("config.json") || !isfile("tsv_config.json")
        @warn "config.json or tsv_config.json not found in current directory. FVM solver cannot run. Returning Inf."
        return Inf
    end

    try
        NX = 10
        NY = 10
        NZ = 30
        if config.tsv.density !== nothing
            NX = config.tsv.density.gx
            NY = config.tsv.density.gy
        end

        # ヘッドレス描画
        ENV["GKSwstype"] = "100"
        
        # q3d の呼び出し
        Main.q3d(NX, NY, NZ, "cg", "gs";
                 epsilon=config.epsilon, par="sequential", is_steady=true,
                 snapshot_path=temp_snapshot, mu=mu)

        if isfile(temp_snapshot)
            data = JLD2.load(temp_snapshot)
            theta = data["theta"]
            tmax = get_tmax(vec(theta))
            return tmax
        else
            @warn "Snapshot file was not generated by FVM solver. Returning Inf."
            return Inf
        end
    catch e
        @warn "FVM solver execution failed: $e. Returning Inf."
        return Inf
    finally
        if isfile(temp_snapshot)
            rm(temp_snapshot, force=true)
        end
    end
end

"""
    get_fitness(mu::Vector{Float64}, model::AbstractInterpolator, basis::Matrix{Float64}, mean_field::Vector{Float64}, config::ModelConfig; penalty::Float64=1000.0, use_fvm_on_extrapolation::Bool=false)::Float64

個体の適合度を算出する。通常はROMを利用し、外挿判定時はペナルティ付きの適合度、
あるいはFVM再検証を起動して真の最高温度を取得する。
"""
function get_fitness(mu::Vector{Float64}, model::AbstractInterpolator, basis::Matrix{Float64}, mean_field::Vector{Float64}, config::ModelConfig; penalty::Float64=1000.0, use_fvm_on_extrapolation::Bool=false)::Float64
    reliable = is_reliable(model, mu)
    
    if !reliable
        @warn "Extrapolation detected for mu! Applying penalty." mu
        if use_fvm_on_extrapolation
            return solve_thermal_fvm(mu, config)
        else
            theta = evaluate_rom(model, basis, mean_field, mu)
            tmax = get_tmax(theta)
            return tmax + penalty
        end
    else
        theta = evaluate_rom(model, basis, mean_field, mu)
        return get_tmax(theta)
    end
end

"""
    get_fitness(mu::Vector{Float64}, model::AbstractInterpolator, config::ModelConfig; penalty::Float64=1000.0)::Float64

個体の適合度を算出する（basis/mean_field を持たない場合のフォールバック）。
外挿領域の場合は FVM を起動し、内挿領域の場合は ROM 評価に必要な basis / mean_field がないためエラーを投げる。
"""
function get_fitness(mu::Vector{Float64}, model::AbstractInterpolator, config::ModelConfig; penalty::Float64=1000.0)::Float64
    reliable = is_reliable(model, mu)
    if !reliable
        @warn "Extrapolation detected for mu! Running FVM." mu
        return solve_thermal_fvm(mu, config)
    else
        error("basis and mean_field must be provided to evaluate fitness with ROM model in interpolation region.")
    end
end

"""
    verify_elites(elites::AbstractVector, model::AbstractInterpolator, basis::Matrix{Float64}, mean_field::Vector{Float64}, config::ModelConfig; enable_fvm_revalidation::Bool=true, error_threshold::Float64=5.0, enable_error_warning::Bool=true)

エリート個体に対してFVM物理ソルバーを実行し、ROM予測値と比較して誤差を記録する。
`enable_fvm_revalidation`が`true`の場合にのみFVMを実行し、適合度をFVM解析結果で更新する。
"""
function verify_elites(
    elites::AbstractVector,
    model::AbstractInterpolator,
    basis::Matrix{Float64},
    mean_field::Vector{Float64},
    config::ModelConfig;
    enable_fvm_revalidation::Bool=true,
    error_threshold::Float64=5.0,
    enable_error_warning::Bool=true
)
    if !enable_fvm_revalidation
        return elites
    end

    for elite in elites
        try
            # ROMによる予測最高温度を計算
            theta_rom = evaluate_rom(model, basis, mean_field, elite.mu)
            tmax_rom = get_tmax(theta_rom)

            # FVMによる厳密な熱解析を実行
            tmax_fvm = solve_thermal_fvm(elite.mu, config)

            # 予測誤差を記録
            error_val = abs(tmax_fvm - tmax_rom)
            @info "ROM vs FVM comparison: ROM = $tmax_rom, FVM = $tmax_fvm, Absolute Error = $error_val"

            # 誤差閾値チェックと警告出力 (Requirement 3.3)
            if enable_error_warning && error_val > error_threshold
                @warn "ROM vs FVM prediction error exceeds threshold! Error = $error_val (Threshold = $error_threshold)"
            end

            # 結果が有限かつ有効な場合、適合度に反映
            if isfinite(tmax_fvm) && tmax_fvm != Inf
                elite.fitness = tmax_fvm
                elite.is_fvm_verified = true
            else
                @warn "FVM revalidation returned invalid value (Inf/NaN). Setting fitness to Inf and marking as unverified."
                elite.fitness = Inf
                elite.is_fvm_verified = false
            end
        catch e
            @error "Failed to run FVM revalidation for elite individual: $e"
            elite.fitness = Inf
            elite.is_fvm_verified = false
        end
    end

    return elites
end

end # module
